name: tk.slides

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.1+1
  bloc_pattern: any
  provider: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  flutter_web_test: any
  test: any 

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
  flutter_web_test:
    path: ../../packages/flutter_web_test
  # tried this to fix widget tests but did not work
  #html: 
  #  path: /usr/lib/dart/lib/html
  bloc_pattern: 
    git:
      url: https://github.com/jacobaraujo7/bloc-pattern.git
      ref: web
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web
      
# added per https://github.com/flutter/flutter/issues/32540
flutter:
  uses-material-design: true
